apiVersion: v1
kind: Secret
metadata:
  name: mms-kogitouser-password
  # corresponds to user.spec.passwordSecretKeyRef.name
type: Opaque
stringData:
  password: r3dh4t2021!
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: mms-scram-kogitouser
spec:
  passwordSecretKeyRef:
    name: mms-kogitouser-password
    # Match to metadata.name of the User Secret
    key: password
  username: "kogitouser"
  db: "admin" #
  mongodbResourceRef:
    name: "red-replica-set"
    # Match to MongoDB resource using authenticaiton
  roles:
  - db: "admin"
    name: "clusterAdmin"
  - db: "admin"
    name: "userAdminAnyDatabase"
  - db: "admin"
    name: "readWrite"
  security:
    authentication:
      enabled : true
      modes: ["SCRAM"]

    