apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
spec:
  replicas: 1
  version: 4.4.4
  adminCredentials: ops-manager-admin-secret

  # optional. Disabled by default. Creates an additional service to make Ops Manager reachable from
  # outside of the Kubernetes cluster.
  externalConnectivity:
    # LoadBalancer|NodePort
    type: LoadBalancer
  # the application database backing Ops Manager. Replica Set is the only supported type
  # Application database has the SCRAM-SHA authentication mode always enabled
  applicationDatabase:
    members: 3
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: external-mongodb
spec:
  type: ReplicaSet
  members: 3

  # Using a version >= 4.0 will enable SCRAM-SHA-256 authentication
  # setting a version < 4.0 will enable SCRAM-SHA-1/MONGODB-CR authentication
  version: 4.0.4-ent
  persistent: true
  opsManager:
    configMapRef:
      name: ops-manager-connection
  credentials: external-mongodb-secret
  # "multiple" persistence allows to mount different directories to different
  # Persistent Volumes
 # persistence:
   # multiple:
   #   data:
     #   storage: 10Gi
    #  journal:
      #  storage: 1Gi
       # labelSelector:
       #   matchLabels:
        #    app: "my-app"
     # logs:
      #  storage: 500M
      #  storageClass: standard
  #security:
   # authentication:
    #  enabled: true
     # modes: ["SCRAM"] # Valid authentication modes are "SCRAM' and "X509"
---
apiVersion: mongodb.com/v1
kind: MongoDBUser
metadata:
  name: mongo-user
spec:
  passwordSecretKeyRef:
    name: kogito-user-secret # the name of the secret that stores this user's password
    key: Password # the key in the secret that stores the password
  username: kogitouser
  db: kogito_dataindex
  mongodbResourceRef:
    name: ops-manager # The name of the MongoDB resource this user will be added to
  roles:
    - db: kogito_dataindex
      name: dbOwner
    - db: kogito_dataindex
      name: clusterAdmin
    - db: kogito_dataindex
      name: userAdminAnyDatabase
