apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: red-standalone
spec:
  version: 4.2.2-ent
  opsManager:
    configMapRef:
      name: red-project-config
  credentials: red-orga-api-key
  type: Standalone
  persistent: true