apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: oc-start-build
spec:
  inputs:
    params:
      - name: componentName
        default: sample
        description: The name of the component
  steps:
    - name: build-image
      image: 'quay.io/openshift/origin-cli:latest'
      command:
        - /usr/bin/oc
      args:
        - start-build
        - $(inputs.params.componentName)
        - '--follow'