kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    org.kie.kogito/managed-by: Kogito Operator
    org.kie.kogito/operator-crd: KogitoDataIndex
  name: notation-protobuf-files
  labels:
    app: notation 
data:
  computeNotation.proto: |-
    syntax = "proto2"; 
    package org.redhat.credit.computeNotation; 
    import "kogito-index.proto";
    import "kogito-types.proto";
    option kogito_model = "ComputeNotation";
    option kogito_id = "computeNotation";
    /* @Indexed */ 
    message Bilan { 
        option java_package = "org.redhat.credit.computeNotation";
        /* @Field(store = Store.YES) */ 
        optional double dl = 1; 
        /* @Field(store = Store.YES) */ 
        optional double ee = 2; 
        /* @Field(store = Store.YES) */ 
        optional double fl = 3; 
        /* @Field(store = Store.YES) */ 
        optional double fm = 4; 
        /* @Field(store = Store.YES) */ 
        optional double ga = 5; 
        /* @Field(store = Store.YES) */ 
        optional double gg = 6; 
        /* @Field(store = Store.YES) */ 
        optional double hn = 7; 
        /* @Field(store = Store.YES) */ 
        optional double hp = 8; 
        /* @Field(store = Store.YES) */ 
        optional double hq = 9; 
        /* @Field(store = Store.YES) */ 
        optional string siren = 10; 
        /* @Field(store = Store.YES) */ 
        repeated Variable variables = 11; 
    }
    /* @Indexed */ 
    message ComputeNotation { 
        option java_package = "org.redhat.credit.computeNotation";
        /* @Field(store = Store.YES)
     @VariableInfo(tags="") */ 
        optional Notation _notation = 1; 
        /* @Field(store = Store.YES)
     @VariableInfo(tags="") */ 
        optional Bilan bilan = 2; 
        /* @Field(store = Store.YES) */ 
        optional string id = 3; 
        /* @Field(store = Store.YES)
     @VariableInfo(tags="") */ 
        optional Variable rentab13 = 4; 
        /* @Field(store = Store.YES)
     @VariableInfo(tags="") */ 
        optional Variable strfin36 = 5; 
        /* @Field(store = Store.YES) */ 
        optional org.kie.kogito.index.model.KogitoMetadata metadata = 6; 
    }
    /* @Indexed */ 
    message Notation { 
        option java_package = "org.redhat.credit.computeNotation";
        /* @Field(store = Store.YES) */ 
        optional double decoupageSectoriel = 1; 
        /* @Field(store = Store.YES) */ 
        optional string note = 2; 
        /* @Field(store = Store.YES) */ 
        optional string orientation = 3; 
        /* @Field(store = Store.YES) */ 
        optional double score = 4; 
        /* @Field(store = Store.YES) */ 
        optional string typeAiguillage = 5; 
    }
    /* @Indexed */ 
    message Variable { 
        option java_package = "org.redhat.credit.computeNotation";
        /* @Field(store = Store.YES) */ 
        optional string type = 1; 
        /* @Field(store = Store.YES) */ 
        optional double value = 2; 
    }
