kind: ConfigMap
apiVersion: v1
metadata:
  name: eligibility-properties
data:
  application.properties : |-
    # Maximum Java heap to be used during the native image generation
    quarkus.native.native-image-xmx=4g
    
    #force index of the model 
    quarkus.index-dependency.model.group-id=org.redhat.bbank
    quarkus.index-dependency.model.artifact-id=model
    
    #rest client 
    org.redhat.bbank.eligibility.rest.CompaniesRemoteService/mp-rest/url=http://companies-svc-bbank-apps.apps.ocp4.ouachani.net
    org.redhat.bbank.eligibility.rest.CompaniesRemoteService/mp-rest/scope=javax.enterprise.context.ApplicationScoped
    
    #infinispan 
    quarkus.infinispan-client.sasl-mechanism=PLAIN
    quarkus.infinispan-client.server-list=kogito-infinispan:11222
    quarkus.infinispan-client.use-auth=true
    quarkus.infinispan-client.auth-username=developer
    quarkus.infinispan-client.auth-password=WS5l2ffp7DuemF3s
  
    # OIDC server (keycloak) connection config
    quarkus.oidc.auth-server-url=https://keycloak-bbank-apps.apps.ocp4.ouachani.org/auth/realms/bbank-apps
    quarkus.oidc.client-id=bbank-sso-client
    quarkus.oidc.credentials.secret=secret
    # Endpoint security configuration
    quarkus.http.auth.permission.authenticated.paths=/*
    quarkus.http.auth.permission.authenticated.policy=authenticated
    
    #kogito (data-index)
    kogito.service.url=http://localhost:8080
    kogito.dataindex.http.url=data-index-bbank-apps.apps.ocp4.ouachani.net
    kogito.dataindex.ws.url=ws://data-index:8080
    
    # kafka eligibility service 
    kafka.bootstrap.servers=kogito-kafka-kafka-bootstrap.bbank-apps.svc:9092
    
    mp.messaging.incoming.eligibilityapplication.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.incoming.eligibilityapplication.connector=smallrye-kafka
    mp.messaging.incoming.eligibilityapplication.topic=eligibilityapplication
    mp.messaging.incoming.eligibilityapplication.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    #mp.messaging.outgoing.noteapplication.auto.offset.reset=earliest

    mp.messaging.outgoing.noteligible.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.noteligible.connector=smallrye-kafka
    mp.messaging.outgoing.noteligible.topic=noteligible
    mp.messaging.outgoing.noteligible.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.eligible.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.eligible.connector=smallrye-kafka
    mp.messaging.outgoing.eligible.topic=eligible
    mp.messaging.outgoing.eligible.value.serializer=org.apache.kafka.common.serialization.StringSerializer
    
    #kafka properties kogito event 
    mp.messaging.outgoing.kogito-jobs-events.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.kogito-jobs-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-jobs-events.topic=kogito-jobs-events
    mp.messaging.outgoing.kogito-jobs-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-processdomain-events.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.kogito-processdomain-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-processdomain-events.topic=kogito-processdomain-events
    mp.messaging.outgoing.kogito-processdomain-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-usertaskdomain-events.bootstrap.servers=${kafka.bootstrap.servers} 
    mp.messaging.outgoing.kogito-usertaskdomain-events.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.kogito-usertaskdomain-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-usertaskdomain-events.topic=kogito-usertaskdomain-events
    mp.messaging.outgoing.kogito-usertaskdomain-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-processinstances-events.bootstrap.servers=${kafka.bootstrap.servers}
    mp.messaging.outgoing.kogito-processinstances-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-processinstances-events.topic=kogito-processinstances-events
    mp.messaging.outgoing.kogito-processinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-usertaskinstances-events.bootstrap.servers=${kafka.bootstrap.servers}   
    mp.messaging.outgoing.kogito-usertaskinstances-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-usertaskinstances-events.topic=kogito-usertaskinstances-events
    mp.messaging.outgoing.kogito-usertaskinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-variables-events.bootstrap.servers=${kafka.bootstrap.servers}    
    mp.messaging.outgoing.kogito-variables-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-variables-events.topic=kogito-variables-events
    mp.messaging.outgoing.kogito-variables-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer