kind: ConfigMap
apiVersion: v1
metadata:
  name: notation-properties
data:
  application.properties : |-
    # Maximum Java heap to be used during the native image generation
    quarkus.native.native-image-xmx=4g
    quarkus.http.cors=true
    kogito.service.url=http://notation-bbankapps-kevent.apps.cluster-e80d.e80d.example.opentlc.com
    kogito.dataindex.http.url=http://data-index-bbankapps-kevent.apps.cluster-e80d.e80d.example.opentlc.com
    kogito.dataindex.ws.url=ws://data-index:8080
    #index of model (jandex)
    quarkus.index-dependency.model.group-id=org.redhat.bbank
    quarkus.index-dependency.model.artifact-id=model
    infinispan.remote.sasl-mechanism=PLAIN
    infinispan.remote.server-list=kogito-infinispan:11222
    infinispan.remote.trust-store-file-name=/home/kogito/certs/infinispan/truststore.p12
    infinispan.remote.trust-store-password=changeit
    infinispan.remote.trust-store-type=PKCS12
    infinispan.remote.use-auth=true
    kafka.bootstrap.servers=kogito-kafka-kafka-bootstrap.bbankapps-kevent.svc:9092
    quarkus.infinispan-client.sasl-mechanism=PLAIN
    quarkus.infinispan-client.server-list=kogito-infinispan:11222
    quarkus.infinispan-client.trust-store=/home/kogito/certs/infinispan/truststore.p12
    quarkus.infinispan-client.trust-store-password=changeit
    quarkus.infinispan-client.trust-store-type=PKCS12
    quarkus.infinispan-client.use-auth=true
    mp.messaging.incoming.kogito_incoming_stream.connector=smallrye-http
    mp.messaging.outgoing.kogito_outgoing_stream.connector=smallrye-http
    mp.messaging.outgoing.kogito_outgoing_stream.url=${K_SINK}
