apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: notation
spec:
  replicas: 1
  image: quay.io/mouachan/notation:1.1
  # Reference to the KogitoInfra resource with the Knative Broker binding
  infra:
  - kogito-knative-infra
  - kogito-infinispan-infra