apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: companies-svc
spec:
  template:
    metadata:
      name: companies-svc-v2
      annotations:
        # disable istio-proxy injection
        sidecar.istio.io/inject: "false"
        # the minimum number of pods to scale down to
        autoscaling.knative.dev/minScale: "1"
        # Target 10 crud-requests per pod.
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/metric: "rps"
    spec:
      containers:
        - image: >-
            quay.io/mouachan/companies-svc:3.0
          env:
            - name: JAVA_OPTS
              value: "-Dvertx.cacheDirBase=/work/vertx"
            - name: MONGODB_CONNECTION_STRING
              value: 'mongodb://admcomp:r3dhat2020!@mongodb:27017/companies'
      imagePullSecrets:
        - name: quay-secret




