apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: bbank-sso-client
  labels:
    app: bbank-sso
spec:
  realmSelector:
     matchLabels:
      app: bbank-sso
  client:
    clientId: bbank-sso-client
