kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: bbank-ui
  namespace: bbank-apps
  labels:
    app: bbank-ui
    app.kubernetes.io/component: bbank-ui
    app.kubernetes.io/instance: bbank-ui
    deployment: bbank-ui
    name: bbank-ui
spec:
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12'
  source:
    type: Git
    git:
      uri: 'http://github.com/mouachan/bbank-apps'
    contextDir: /bbank-ui
    sourceSecret:
      name: github
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: bbank-ui
  namespace: bbank-apps
  labels:
    app: bbank-ui
    app.kubernetes.io/component: bbank-ui
    app.kubernetes.io/instance: bbank-ui
    deployment: bbank-ui
    name: bbank-ui
  spec:
    containers:
      - name: bbank-ui
        image: >-
          image-registry.openshift-image-registry.svc:5000/bbank-apps/bbank-ui
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
          - name: volume-config
            mountPath: /opt/app-route/src/config