apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: eligibility
spec:
  type: Binary
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  annotations:
    org.kie.kogito/managed-by: Kogito Operator
    org.kie.kogito/operator-crd: KogitoRuntime
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    app: eligibility
    eligibility: process
  name: eligibility
spec:
  serviceLabels:
    app: eligibility
  infra:
    - kogito-infinispan-infra
    - kogito-kafka-infra
  resources:
    requests:
      memory: 4Gi 
    limits:
      memory: 6Gi 