{
 "title": "Loan Dashboard V2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total loan requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_process_instance_started_total{process_id='loanValidation'})"
    }
   ]
  },
  {
   "title": "Open Loan requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_process_instance_running_total{process_id='loanValidation'})"
    }
   ]
  },
  {
   "title": "Canceled loan requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_process_instance_completed_total{status=\"3\", process_id='loanValidation'})"
    }
   ]
  },
  {
   "title": "Completed loan requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kie_process_instance_completed_total{status=\"2\", process_id='loanValidation'})"
    }
   ]
  },
  {
   "title": "Process invoked",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kie_process_instance_completed_total"
    }
   ]
  },
  {
   "title": "Loan approved",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 4 },
   "targets": [
    { "expr": "loan_approved_total" }
   ]
  },
  {
   "title": "Rule execution time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(drl_match_fired_nanosecond_sum[1m])",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Rules applied",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "drl_match_fired_nanosecond_count"
    }
   ]
  },
  {
   "title": "Loan rejected",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 12 },
   "targets": [
    { "expr": "loan_rejected_total" }
   ]
  },
  {
   "title": "Loan request processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_process_instance_duration_seconds_sum[1m])/avg_over_time(kie_process_instance_duration_seconds_count[1m])",
     "legendFormat": "{{process_id}}"
    }
   ]
  },
  {
   "title": "Approved notation",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "targets": [
    { "expr": "notation_approved_total" }
   ]
  },
  {
   "title": "Rejected Notation",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 20 },
   "targets": [
    { "expr": "notation_rejected_total" }
   ]
  }
 ]
}