apiVersion: app.kiegroup.org/v1alpha1
kind: KogitoRuntime
metadata:
  annotations:
    org.kie.kogito/managed-by: Kogito Operator
    org.kie.kogito/operator-crd: KogitoRuntime
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    app: loan
    loanValidation: process
  name: loan
spec:
  serviceLabels:
    app: loan
  infinispan:
    useKogitoInfra: true
  kafka:
    useKogitoInfra: true