apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
    monitoring-key: "kogito"
  name: kogito-monitor-services
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: http
  selector:
    matchLabels:
      monitoring: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: eligibility
    name: eligibility
  name: eligibility
  namespace: bbank-apps
spec:
  endpoints:
  - path: /metrics
    targetPort: 8080
    scheme: http
  namespaceSelector:
    matchNames:
    - bbank-apps
  selector:
    matchLabels:
      app: eligibility
      monitoring-key: eligibility
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: notation
    name: notation
  name: notation
  namespace: bbank-apps
spec:
  endpoints:
  - path: /metrics
    targetPort: 8080
    scheme: http
  namespaceSelector:
    matchNames:
    - bbank-apps
  selector:
    matchLabels:
      app: notation
      monitoring-key: notation
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: loan
    name: loan
  name: loan
  namespace: bbank-apps
spec:
  endpoints:
  - path: /metrics
    targetPort: 8080
    scheme: http
  namespaceSelector:
    matchNames:
    - bbank-apps
  selector:
    matchLabels:
      app: loan
      monitoring-key: loan