apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: task-console
spec:
  type: Binary
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: task-console
  namespace: bbankapps
  labels:
    app: task-console
spec:
  env:
    - name: HTTP_PORT
      value: '8080'
  replicas: 1
