/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_luben_zstd_ZstdDictDecompress */

#ifndef _Included_com_github_luben_zstd_ZstdDictDecompress
#define _Included_com_github_luben_zstd_ZstdDictDecompress
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_luben_zstd_ZstdDictDecompress_SHARED_LOCK_CLOSED
#define com_github_luben_zstd_ZstdDictDecompress_SHARED_LOCK_CLOSED -1L
/*
 * Class:     com_github_luben_zstd_ZstdDictDecompress
 * Method:    init
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_github_luben_zstd_ZstdDictDecompress_init
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_github_luben_zstd_ZstdDictDecompress
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_luben_zstd_ZstdDictDecompress_free
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
