apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: ping-source
spec:
  schedule: "*/2 * * * *"
  contentType: "application/json"
  jsonData: '{"age":3,"amount":50000,"bilan":{"gg":5,"ga":2,"hp":1,"hq":2,"dl":50,"ee":2,"siren":"423646512","variables":[]},"ca":200000,"eligible":false,"msg":"string","nbEmployees":10,"notation":{"decoupageSectoriel":0,"note":"string","orientation":"string","score":0,"typeAiguillage":"string"},"publicSupport":true,"siren":"423646512","typeProjet":"IRD"}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default