apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: sequence
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: v1
        kind: Service
        name: eligibility
    - ref:
        apiVersion: v1
        kind: Service
        name: notation
    
  reply:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: default