apiVersion: v1
data:
  password: YWxpY2UK
  username: YWxpY2U=
kind: Secret
metadata:
  creationTimestamp: "2020-10-20T10:01:34Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:password: {}
        f:username: {}
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"4cdc9aa6-6f50-4f6a-9833-30bd7fac407e"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:type: {}
    manager: keycloak-operator
    operation: Update
    time: "2020-10-20T10:01:34Z"
  name: credential-kogito-alice-bbank
  namespace: bbank
  ownerReferences:
  - apiVersion: keycloak.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: KeycloakRealm
    name: kogito
    uid: 4cdc9aa6-6f50-4f6a-9833-30bd7fac407e
  resourceVersion: "33452430"
  selfLink: /api/v1/namespaces/bbank/secrets/credential-kogito-alice-bbank
  uid: 3ba9aacd-aed1-4571-8140-da99dbbb5d72
type: Opaque
