apiVersion: v1
data:
  password: aXR7U2plajd2aWF9MjMwMg==
  username: bW91YWNoYW4=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"password":"aXR7U2plajd2aWF9MjMwMg==","username":"bW91YWNoYW4="},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":"2020-09-15T10:49:16Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:password":{},"f:username":{}},"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:type":{}},"manager":"oc","operation":"Update","time":"2020-09-15T10:49:16Z"}],"name":"github","namespace":"bbank-apps","resourceVersion":"89237","selfLink":"/api/v1/namespaces/bbank-apps/secrets/github","uid":"fb89139c-1cc3-4017-a7cd-6232c163fa28"},"type":"kubernetes.io/basic-auth"}
  creationTimestamp: "2020-09-15T10:49:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:password: {}
        f:username: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:type: {}
    manager: oc
    operation: Update
    time: "2020-10-19T14:26:36Z"
  name: github
  resourceVersion: "32713861"
  selfLink: /api/v1/namespaces/bbank-apps/secrets/github
  uid: fb89139c-1cc3-4017-a7cd-6232c163fa28
type: kubernetes.io/basic-auth
